# Generated by Django 3.2 on 2021-06-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('photo', models.ImageField(blank=True, upload_to='myimage')),
                ('event_title', models.TextField(blank=True, max_length=5000)),
                ('event_start_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('todo_title', models.TextField(blank=True, max_length=5000)),
                ('todo_description', models.TextField(blank=True, max_length=5000)),
                ('todo_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
