# Generated by Django 3.2 on 2021-06-15 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210614_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 15, 11, 55, 35, 512119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 15, 11, 55, 35, 512119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='todo_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 15, 11, 55, 35, 512119, tzinfo=utc)),
        ),
    ]
