# Generated by Django 3.2 on 2021-06-16 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210615_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 13, 32, 11, 855283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 13, 32, 11, 855283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='todo_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 16, 13, 32, 11, 855283, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
