# Generated by Django 3.2 on 2021-06-17 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210617_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 17, 6, 23, 9, 961672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 17, 6, 23, 9, 961672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='todo_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 17, 6, 23, 9, 962670, tzinfo=utc)),
        ),
    ]
