# Generated by Django 3.2 on 2021-06-20 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210618_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 20, 13, 41, 57, 17838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 20, 13, 41, 57, 17838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='todo_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 20, 13, 41, 57, 17838, tzinfo=utc)),
        ),
    ]
